source "https://rubygems.org"

gem "rails",  "3.2.3"
gem "mysql2", "~> 0.3.11"
gem "jquery-rails", "~> 2.0.2"

group :assets do
  gem "sass-rails",   "~> 3.2.3"
  gem "therubyracer", "~> 0.10.0", platform: :ruby
  gem "uglifier",     "~> 1.2.4"
end

gem "authlogic", "~> 3.1.0"
gem "cancan", "~> 1.6.7"